// <auto-generated />
using System;
using Maliev.ComplianceService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.ComplianceService.Infrastructure.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    [Migration("20260110141718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.ComplianceService.Domain.Entities.ComplianceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_date");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("WorkAuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_authorization_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_alerts_employee");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("idx_alerts_unresolved")
                        .HasFilter("is_resolved = FALSE");

                    b.HasIndex("WorkAuthorizationId")
                        .HasDatabaseName("idx_alerts_auth");

                    b.ToTable("compliance_alerts", (string)null);
                });

            modelBuilder.Entity("Maliev.ComplianceService.Domain.Entities.WorkAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AccessRevocationSentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_revocation_sent_date");

                    b.Property<int>("AuthorizationType")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_type");

                    b.Property<int>("ComplianceStatus")
                        .HasColumnType("integer")
                        .HasColumnName("compliance_status");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuing_authority");

                    b.Property<int?>("LastExpirationAlertThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("last_expiration_alert_threshold");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("RightToWorkDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("right_to_work_document_id");

                    b.Property<Guid>("RowVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("row_version");

                    b.Property<int?>("SponsorshipStatus")
                        .HasColumnType("integer")
                        .HasColumnName("sponsorship_status");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceStatus")
                        .HasDatabaseName("idx_work_auth_status");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_work_auth_employee");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("idx_work_auth_expiration");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_work_auth_active")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("EmployeeId", "AuthorizationType")
                        .IsUnique()
                        .HasDatabaseName("uq_active_auth_per_type")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("work_authorizations", (string)null);
                });

            modelBuilder.Entity("Maliev.ComplianceService.Domain.Entities.ComplianceAlert", b =>
                {
                    b.HasOne("Maliev.ComplianceService.Domain.Entities.WorkAuthorization", "WorkAuthorization")
                        .WithMany("ComplianceAlerts")
                        .HasForeignKey("WorkAuthorizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkAuthorization");
                });

            modelBuilder.Entity("Maliev.ComplianceService.Domain.Entities.WorkAuthorization", b =>
                {
                    b.Navigation("ComplianceAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
